import os


DATABASE_URL = os.getenv(
    "DATABASE_URL", "postgresql+asyncpg://user:password@user_db/user_db"
)

KEYCLOAK_CLIENT_PUBLIC_KEY = os.getenv(
    "KEYCLOAK_CLIENT_PUBLIC_KEY",
    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx3V7fKMuAO055R158iL18lehMdjFOZr1P7tmvrbQK3v/9hgbB6ROhOAmT1Aj+ml7rNMb+eMeJEPvDuE5sQm9hMUAU88bWC/pqWyCIegEEWEixeItUrBZLxEsmWagF5wFc90juNxu0qXEf2r/oKuRSdWuJXRx4IRkZm24XzlTLI/z7DZUvRL3t4e/XpnLgb8dVRw/xSmrqAFnbXbRaESDpp77KhTKlhxkVBiT5rBKRwAwI3a7kEYEFtvX3wpRimGPOh/uogtbHn1wKPmFLfpcchu6eIozvWTcVPkfPPSqOwS7HyYlHUdMS+MSjKlmM9dBCh81kgxRWbXLkz0vf6dQ3QIDAQAB",
)

KEYCLOAK_HOST = os.getenv("KEYCLOAK_HOST", "http://sm_keycloak:8080")
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM", "paw_connect")
KEYCLOAK_CLIENT_ID = os.getenv("KEYCLOAK_CLIENT_ID", "admin-cli")
KEYCLOAK_CLIENT_SECRET_KEY = os.getenv(
    "KEYCLOAK_CLIENT_SECRET_KEY", "wSVxDu1FL5SIbdDlqEpr9wohnB8bxYO7"
)


MINIO_ENDPOINT = os.getenv("MINIO_HOST", "sm_minio:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "minio_access_key")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "minio_secret_key")
MINIO_BUCKET = os.getenv("MINIO_BUCKET", "user-media")

ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST", "http://sm_elasticsearch:9200")

print(
    f"""
LOADED CONFIG:
DATABASE_URL: {DATABASE_URL}

KEYCLOAK_CLIENT_PUBLIC_KEY: {KEYCLOAK_CLIENT_PUBLIC_KEY}
KEYCLOAK_HOST: {KEYCLOAK_HOST}
KEYCLOAK_REALM: {KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID: {KEYCLOAK_CLIENT_ID}
KEYCLOAK_CLIENT_SECRET_KEY: {KEYCLOAK_CLIENT_SECRET_KEY}

MINIO_ENDPOINT: {MINIO_ENDPOINT}
MINIO_ACCESS_KEY: {MINIO_ACCESS_KEY}
MINIO_SECRET_KEY: {MINIO_SECRET_KEY}
MINIO_BUCKET: {MINIO_BUCKET}

ELASTICSEARCH_HOST: {ELASTICSEARCH_HOST}
"""
)
